#!/sbin/openrc-run
command_background="yes"
pidfile="/var/run/testbitd.pid"
name="testbitd"
description="testbitd - A test server for bitbit."
command="testbitd"
command_args="--db /var/lib/bitbit/bitbit.sqlite3 \
	--backup /var/lib/bitbit/backup"
start_stop_daemon_args="--stdout /var/log/testbitd.log \
	--stderr /var/log/testbitd.err"
stopsig="SIGINT"

depend() {
	need net
}

start_pre() {
	if [[ ! -d "/var/lib/bitbit" ]]; then
		eerror "Please create the directory /var/lib/bitbit"
		return 1
	fi
	if [[ ! -d "/var/lib/bitbit/backup" ]]; then
		eerror "Please create the directory /var/lib/bitbit/backup"
		return 1
	fi
	return 0
}
